taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/ruthmelese/Desktop/data-engineering-proj1/ds3022-data-project-1/transform.duckdb
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
